package com.light.noteai.dal.mapper;

import com.light.noteai.mapper.po.Notes;
import com.light.noteai.mapper.po.NotesExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface NotesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    long countByExample(NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int deleteByExample(NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int insert(Notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int insertSelective(Notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    List<Notes> selectByExampleWithBLOBsWithRowbounds(NotesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    List<Notes> selectByExampleWithBLOBs(NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    List<Notes> selectByExampleWithRowbounds(NotesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    List<Notes> selectByExample(NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    Notes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int updateByExampleSelective(@Param("record") Notes record, @Param("example") NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Notes record, @Param("example") NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int updateByExample(@Param("record") Notes record, @Param("example") NotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int updateByPrimaryKeySelective(Notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Notes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    int updateByPrimaryKey(Notes record);

    @Select("SELECT id, title, content, created_at, updated_at FROM notes ORDER BY updated_at DESC")
    List<Notes> findAll();

    @Select("SELECT id, title, content, created_at, updated_at FROM notes WHERE title=content")
    List<Notes> getAllUnWrittenNotes();

    @Select("SELECT id, title, content, created_at, updated_at FROM notes ORDER BY updated_at DESC LIMIT #{pageSize} OFFSET #{startIndex}")
    List<Notes> findByPage(@Param("startIndex") int startIndex, @Param("pageSize") int pageSize);


    @Select("SELECT * FROM notes\n" +
            "    WHERE title LIKE CONCAT('%', #{keyword}, '%')\n" +
            "    ORDER BY id DESC\n" +
            "    LIMIT #{offset}, #{limit}")
    List<Notes> findNotesByKeyword(@Param("keyword") String keyword, @Param("offset") int offset, @Param("limit") int limit);


    @Insert("INSERT INTO notes(title, content, created_at, updated_at) VALUES(#{title}, #{content}, NOW(), NOW())")
    @Options(useGeneratedKeys = true, keyProperty = "id")
    int create(Notes note);

    @Update("UPDATE notes SET title = #{title}, content = #{content}, updated_at = NOW() WHERE id = #{id}")
    int update(Notes note);

    @Select("SELECT count(*) FROM notes WHERE title LIKE CONCAT('%', #{keyword}, '%')")
    Integer getTotalNotesByKeyword(String keyword);

}