package com.light.noteai.mapper.po;

import java.util.Date;

public class Notes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.id
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.title
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.created_at
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.updated_at
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notes.content
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.id
     *
     * @return the value of notes.id
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.id
     *
     * @param id the value for notes.id
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.title
     *
     * @return the value of notes.title
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.title
     *
     * @param title the value for notes.title
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.created_at
     *
     * @return the value of notes.created_at
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.created_at
     *
     * @param createdAt the value for notes.created_at
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.updated_at
     *
     * @return the value of notes.updated_at
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.updated_at
     *
     * @param updatedAt the value for notes.updated_at
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notes.content
     *
     * @return the value of notes.content
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notes.content
     *
     * @param content the value for notes.content
     *
     * @mbg.generated Sun Jun 11 22:14:04 CST 2023
     */
    public void setContent(String content) {
        this.content = content;
    }
}